---
title: A Night In Japan
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: post
email: hello@sarahgill.co.uk
description: A blog about Japan.
baseurl: ''
url: ''
twitter_username: sarahgillatron
github_username: sarahgillatron
theme: minima
plugins:
- jekyll-feed
